### ISSUE TITLE
main.py

### ISSUE THREAD

**Issue by Johcc** [qlt315/UCMEC_COMMAG#1]
Hello, I am a newcomer to machine learning. I would like to ask you some questions about how to implement the model saving and model loading code in your main function.

**Comment by qlt315** [comment]
Hi, you can use **_torch.save()_** to save the actor and critic networks of the PPO agent after or during the training phase:
```
torch.save(agent.actor, 'actor.pth')
torch.save(agent.critic, 'critic.pth')
```

When you need to load the saved agent in the test environment, initialize a PPO agent and use **_torch.load()_** to load the actor and critical networks:
```
agent = PPO_continuous(args)
agent.actor = torch.load('actor.pth')
agent.critic =  torch.load('critic.pth')
```

**Comment by Johcc** [comment]
Thank you very much for your answer
